export const GET_POMPIERS = "GET_POMPIERS";
export const GET_POMPIERS_SUCCESS = "GET_POMPIERS_SUCCESS";
export const GET_POMPIERS_FAIL = "GET_POMPIERS_FAIL";

export const DELETE_POMPIER = "DELETE_POMPIER";
export const DELETE_POMPIER_SUCCESS = "DELETE_POMPIER_SUCCESS";
export const DELETE_POMPIER_FAIL = "DELETE_POMPIER_FAIL";

export const ADD_POMPIER = "ADD_POMPIER";
export const ADD_POMPIER_SUCCESS = "ADD_POMPIER_SUCCESS";
export const ADD_POMPIER_FAIL = "ADD_POMPIER_FAIL";

export const UPDATE_POMPIER = "UPDATE_POMPIER"
export const UPDATE_POMPIER_SUCCESS = "UPDATE_POMPIER_SUCCESS"
export const UPDATE_POMPIER_FAIL = "UPDATE_POMPIER_FAIL"