export const GET_CASERNES = "GET_CASERNES";
export const GET_CASERNES_SUCCESS = "GET_CASERNES_SUCCESS";
export const GET_CASERNES_FAIL = "GET_CASERNES_FAIL";

export const DELETE_CASERNE = "DELETE_CASERNE";
export const DELETE_CASERNE_SUCCESS = "DELETE_CASERNE_SUCCESS";
export const DELETE_CASERNE_FAIL = "DELETE_CASERNE_FAIL";

export const ADD_CASERNE = "ADD_CASERNE";
export const ADD_CASERNE_SUCCESS = "ADD_CASERNE_SUCCESS";
export const ADD_CASERNE_FAIL = "ADD_CASERNE_FAIL";

export const UPDATE_CASERNE = "UPDATE_CASERNE"
export const UPDATE_CASERNE_SUCCESS = "UPDATE_CASERNE_SUCCESS"
export const UPDATE_CASERNE_FAIL = "UPDATE_CASERNE_FAIL"